import {IrregularVerb} from './irregularverb';
export class VerbLoader {

  public list: IrregularVerb[] = [
    {present: 'arise', past: 'arose', pastParticiple: 'arisen', translation: 'surgir'},
    {present: 'awake', past: 'awoke', pastParticiple: 'awoken', translation: 'despertar(se)'},
    {present: 'bear', past: 'bore', pastParticiple: 'borne', translation: 'soportar'},
    {present: 'beat', past: 'beat', pastParticiple: 'beaten', translation: 'golpear'},
    {present: 'become', past: 'became', pastParticiple: 'become', translation: 'convertirse en'},
    {present: 'begin', past: 'began', pastParticiple: 'begun', translation: 'empezar'},
    {present: 'bend', past: 'bent', pastParticiple: 'bent', translation: 'doblar(se)'},
    {present: 'bet', past: 'bet', pastParticiple: 'bet', translation: 'apostar'},
    {present: 'bid', past: 'bid', pastParticiple: 'bid', translation: 'pujar'},
    {present: 'bind', past: 'bound', pastParticiple: 'bound', translation: 'encuadernar'},
    {present: 'bite', past: 'bit', pastParticiple: 'bitten', translation: 'morder'},
    {present: 'bleed', past: 'bled', pastParticiple: 'bled', translation: 'sangrar'},
    {present: 'blow', past: 'blew', pastParticiple: 'blown', translation: 'soplar'},
    {present: 'break', past: 'broke', pastParticiple: 'broken', translation: 'romper'},
    {present: 'breed', past: 'bred', pastParticiple: 'bred', translation: 'criar'},
    {present: 'bring', past: 'brought', pastParticiple: 'brought', translation: 'traer'},
    {present: 'build', past: 'built', pastParticiple: 'built', translation: 'construir'},
    {present: 'burn', past: 'burnt', pastParticiple: 'burnt', translation: 'quemar(se)'},
    {present: 'burst', past: 'burst', pastParticiple: 'burst', translation: 'estallar'},
    {present: 'buy', past: 'bought', pastParticiple: 'bought', translation: 'comprar'},
    {present: 'cast', past: 'cast', pastParticiple: 'cast', translation: 'tirar'},
    {present: 'catch', past: 'caught', pastParticiple: 'caught', translation: 'coger'},
    {present: 'choose', past: 'chose', pastParticiple: 'chosen', translation: 'elegir'},
    {present: 'cling', past: 'clung', pastParticiple: 'clung', translation: 'aferrarse'},
    {present: 'come', past: 'came', pastParticiple: 'come', translation: 'venir'},
    {present: 'cost', past: 'cost', pastParticiple: 'cost', translation: 'costar'},
    {present: 'creep', past: 'crept', pastParticiple: 'crept', translation: 'arrastrar'},
    {present: 'cut', past: 'cut', pastParticiple: 'cut', translation: 'cortar'},
    {present: 'deal', past: 'dealt', pastParticiple: 'dealt', translation: 'tratar'},
    {present: 'dig', past: 'dug', pastParticiple: 'dug', translation: 'cavar'},
    {present: 'do', past: 'did', pastParticiple: 'done', translation: 'hacer'},
    {present: 'draw', past: 'drew', pastParticiple: 'drawn', translation: 'dibujar'},
    {present: 'dream', past: 'dreamt', pastParticiple: 'dreamt', translation: 'soñar'},
    {present: 'drink', past: 'drank', pastParticiple: 'drunk', translation: 'beber'},
    {present: 'drive', past: 'drove', pastParticiple: 'driven', translation: 'conducir'},
    {present: 'eat', past: 'ate', pastParticiple: 'eaten', translation: 'comer'},
    {present: 'fall', past: 'fell', pastParticiple: 'fallen', translation: 'caer(se)'},
    {present: 'feed', past: 'fed', pastParticiple: 'fed', translation: 'alimentar'},
    {present: 'feel', past: 'felt', pastParticiple: 'felt', translation: 'sentirse'},
    {present: 'fight', past: 'fought', pastParticiple: 'fought', translation: 'pelearse'},
    {present: 'find', past: 'found', pastParticiple: 'found', translation: 'encontrar'},
    {present: 'flee', past: 'fled', pastParticiple: 'fled', translation: 'huir'},
    {present: 'fly', past: 'flew', pastParticiple: 'flown', translation: 'volar'},
    {present: 'forbid', past: 'forbade', pastParticiple: 'forbidden', translation: 'prohibir'},
    {present: 'forget', past: 'forgot', pastParticiple: 'forgotten', translation: 'olvidar(se)'},
    {present: 'forgive', past: 'forgave', pastParticiple: 'forgiven', translation: 'perdonar'},
    {present: 'freeze', past: 'froze', pastParticiple: 'frozen', translation: 'helar(se)'},
    {present: 'get', past: 'got', pastParticiple: 'got', translation: 'conseguir'},
    {present: 'give', past: 'gave', pastParticiple: 'given', translation: 'dar'},
    {present: 'go', past: 'went', pastParticiple: 'gone', translation: 'irse'},
    {present: 'grind', past: 'ground', pastParticiple: 'ground', translation: 'moler'},
    {present: 'grow', past: 'grew', pastParticiple: 'grown', translation: 'crecer'},
    {present: 'hang', past: 'hung', pastParticiple: 'hung', translation: 'colgar'},
    {present: 'have', past: 'had', pastParticiple: 'had', translation: 'haber, tener'},
    {present: 'hear', past: 'heard', pastParticiple: 'heard', translation: 'escuchar'},
    {present: 'hide', past: 'hid', pastParticiple: 'hidden', translation: 'esconder(se)'},
    {present: 'hit', past: 'hit', pastParticiple: 'hit', translation: 'golpear'},
    {present: 'hold', past: 'held', pastParticiple: 'held', translation: 'agarrar(se)'},
    {present: 'hurt', past: 'hurt', pastParticiple: 'hurt', translation: 'hacer daño'},
    {present: 'keep', past: 'kept', pastParticiple: 'kept', translation: 'guardar'},
    {present: 'kneel', past: 'knelt', pastParticiple: 'knelt', translation: 'arrodillarse'},
    {present: 'know', past: 'knew', pastParticiple: 'known', translation: 'saber, conocer'},
    {present: 'lay', past: 'laid', pastParticiple: 'laid', translation: 'poner'},
    {present: 'lead', past: 'led', pastParticiple: 'led', translation: 'llevar'},
    {present: 'lean', past: 'leant', pastParticiple: 'leant', translation: 'apoyarse'},
    {present: 'leap', past: 'leapt', pastParticiple: 'leapt', translation: 'brincar'},
    {present: 'learn', past: 'learnt', pastParticiple: 'learnt', translation: 'aprender'},
    {present: 'leave', past: 'left', pastParticiple: 'left', translation: 'dejar'},
    {present: 'lend', past: 'lent', pastParticiple: 'lent', translation: 'prestar'},
    {present: 'let', past: 'let', pastParticiple: 'let', translation: 'permitir'},
    {present: 'lie', past: 'lay', pastParticiple: 'lain', translation: 'echarse'},
    {present: 'light', past: 'lit', pastParticiple: 'lit', translation: 'encender(se)'},
    {present: 'lose', past: 'lost', pastParticiple: 'lost', translation: 'perder'},
    {present: 'make', past: 'made', pastParticiple: 'made', translation: 'hacer'},
    {present: 'mean', past: 'meant', pastParticiple: 'meant', translation: 'significar'},
    {present: 'meet', past: 'met', pastParticiple: 'met', translation: 'encontrar(se)'},
    {present: 'overcome', past: 'overcame', pastParticiple: 'overcome', translation: 'vencer'},
    {present: 'pay', past: 'paid', pastParticiple: 'paid', translation: 'pagar'},
    {present: 'put', past: 'put', pastParticiple: 'put', translation: 'poner'},
    {present: 'read', past: 'read', pastParticiple: 'read', translation: 'leer'},
    {present: 'ride', past: 'rode', pastParticiple: 'ridden', translation: 'montar'},
    {present: 'ring', past: 'rang', pastParticiple: 'rung', translation: 'sonar'},
    {present: 'rise', past: 'rose', pastParticiple: 'risen', translation: 'levantarse'},
    {present: 'run', past: 'ran', pastParticiple: 'run', translation: 'correr'},
    {present: 'saw', past: 'sawed', pastParticiple: 'sawn', translation: 'serrar'},
    {present: 'say', past: 'said', pastParticiple: 'said', translation: 'decir'},
    {present: 'see', past: 'saw', pastParticiple: 'seen', translation: 'ver'},
    {present: 'seek', past: 'sought', pastParticiple: 'sought', translation: 'buscar'},
    {present: 'sell', past: 'sold', pastParticiple: 'sold', translation: 'vender(se)'},
    {present: 'send', past: 'sent', pastParticiple: 'sent', translation: 'enviar'},
    {present: 'set', past: 'set', pastParticiple: 'set', translation: 'poner'},
    {present: 'sew', past: 'sewed', pastParticiple: 'sewn', translation: 'coser'},
    {present: 'shake', past: 'shook', pastParticiple: 'shaken', translation: 'agitar'},
    {present: 'shear', past: 'sheared', pastParticiple: 'shorn', translation: 'esquilar'},
    {present: 'shine', past: 'shone', pastParticiple: 'shone', translation: 'brillar'},
    {present: 'shoot', past: 'shot', pastParticiple: 'shot', translation: 'disparar'},
    {present: 'show', past: 'showed', pastParticiple: 'shown', translation: 'mostrar'},
    {present: 'shrink', past: 'shrank', pastParticiple: 'shrunk', translation: 'encoger(se)'},
    {present: 'shut', past: 'shut', pastParticiple: 'shut', translation: 'cerrar(se)'},
    {present: 'sing', past: 'sang', pastParticiple: 'sung', translation: 'cantar'},
    {present: 'sink', past: 'sank', pastParticiple: 'sunk', translation: 'hundir(se)'},
    {present: 'sit', past: 'sat', pastParticiple: 'sat', translation: 'sentar(se)'},
    {present: 'sleep', past: 'slept', pastParticiple: 'slept', translation: 'dormir'},
    {present: 'slide', past: 'slid', pastParticiple: 'slid', translation: 'resbalar'},
    {present: 'smell', past: 'smelt', pastParticiple: 'smelt', translation: 'oler'},
    {present: 'sow', past: 'sowed', pastParticiple: 'sown', translation: 'sembrar'},
    {present: 'speak', past: 'spoke', pastParticiple: 'spoken', translation: 'hablar'},
    {present: 'speed', past: 'sped', pastParticiple: 'sped', translation: 'acelerar'},
    {present: 'spell', past: 'spelt', pastParticiple: 'spelt', translation: 'deletrear'},
    {present: 'spend', past: 'spent', pastParticiple: 'spent', translation: 'pasar, gastar'},
    {present: 'spill', past: 'spilt', pastParticiple: 'spilt', translation: 'derramar'},
    {present: 'spit', past: 'spat', pastParticiple: 'spat', translation: 'escupir'},
    {present: 'split', past: 'split', pastParticiple: 'split', translation: 'hender'},
    {present: 'spoil', past: 'spoilt', pastParticiple: 'spoilt', translation: 'estropear(se)'},
    {present: 'spread', past: 'spread', pastParticiple: 'spread', translation: 'extender(se)'},
    {present: 'stand', past: 'stood', pastParticiple: 'stood', translation: 'estar de pie'},
    {present: 'steal', past: 'stole', pastParticiple: 'stolen', translation: 'robar'},
    {present: 'stick', past: 'stuck', pastParticiple: 'stuck', translation: 'pegar(se)'},
    {present: 'sting', past: 'stung', pastParticiple: 'stung', translation: 'picar'},
    {present: 'stink', past: 'stank', pastParticiple: 'stunk', translation: 'apestar'},
    {present: 'strike', past: 'struck', pastParticiple: 'struck', translation: 'golpear'},
    {present: 'strive', past: 'strove', pastParticiple: 'striven', translation: 'esforzarse'},
    {present: 'swear', past: 'swore', pastParticiple: 'sworn', translation: 'jurar'},
    {present: 'sweep', past: 'swept', pastParticiple: 'swept', translation: 'barrer'},
    {present: 'swim', past: 'swam', pastParticiple: 'swum', translation: 'nadar'},
    {present: 'swing', past: 'swung', pastParticiple: 'swung', translation: 'balancear(se)'},
    {present: 'take', past: 'took', pastParticiple: 'taken', translation: 'tomar(se)'},
    {present: 'teach', past: 'taught', pastParticiple: 'taught', translation: 'enseñar'},
    {present: 'tear', past: 'tore', pastParticiple: 'torn', translation: 'romper(se)'},
    {present: 'tell', past: 'told', pastParticiple: 'told', translation: 'contar, decir'},
    {present: 'think', past: 'thought', pastParticiple: 'thought', translation: 'pensar'},
    {present: 'throw', past: 'threw', pastParticiple: 'thrown', translation: 'lanzar'},
    {present: 'tread', past: 'trod', pastParticiple: 'trodden', translation: 'pisar'},
    {present: 'undergo', past: 'underwent', pastParticiple: 'undergone', translation: 'sufrir'},
    {present: 'understand', past: 'understood', pastParticiple: 'understood', translation: 'entender'},
    {present: 'upset', past: 'upset', pastParticiple: 'upset', translation: 'afligir'},
    {present: 'wake', past: 'woke', pastParticiple: 'woken', translation: 'despertar(se)'},
    {present: 'wear', past: 'wore', pastParticiple: 'worn', translation: 'llevar (puesto)'},
    {present: 'weave', past: 'wove', pastParticiple: 'woven', translation: 'tejer'},
    {present: 'weep', past: 'wept', pastParticiple: 'wept', translation: 'llorar'},
    {present: 'win', past: 'won', pastParticiple: 'won', translation: 'ganar'},
    {present: 'wind', past: 'wound', pastParticiple: 'wound', translation: 'enrollar'},
    {present: 'withdraw', past: 'withdrew', pastParticiple: 'withdrawn', translation: 'retirar(se)'},
    {present: 'wring', past: 'wrung', pastParticiple: 'wrung', translation: 'torcer'},
    {present: 'write', past: 'wrote', pastParticiple: 'written', translation: 'escribir'},

  ];

}
